
const characters = {
  airgroove: {
    personality: "She serves as the vice president of the student council and is famously known as the “Empress.” Her mother, a highly accomplished Umamusume, raised her with great care—instilling in her the ideals of Tracen Academy from a young age. Trained under her mother's guidance, she aspires to embody those very principles herself. Despite her dignified image, she has a soft spot for flowers and finds joy in tending to them. She considers Symboli Rudolf, the student council president, a trusted comrade.",
    trait1: "Strength: Skilled at growing flowers.",
    trait2: "Weaknesses: Sensitive to sudden movements and flashing lights.",
    trait3: "Family: Spends the whole year carefully planning her mother's birthday celebration.",
    trait4: "Pre-Race Ritual: Touches up her eyeshadow, then channels her determination.",
    trait5: "Secret: Dislikes insects—except for ladybugs, which she finds adorable.",
    speedpriority: "800-900",
    staminapriority: "400-500",
    powerpriority: "500-600",
    gutspriority: "300-400",
   witspriority: "300-400",
   skill1: "Professor of Curvature",
   skill2: "Straightaway Acceleration",
   skill3: "Homestretch Haste",
   besttotrain: "Focus on speed,then on power,stamina,guts and wits.",  
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Mile and Medium.", 
   okdistance: "Sprint", 
   worstdistance: "Long", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Air_Groove_%28Icon%29.png&width=300",
   profilename: "Air Groove",
   profilesubtitle: " 'Empress' ",
   rarity: "★★",
   type: "Speed/Stamina",
   distance: "Mile/Medium",
   style: "Pace/Late",
   birthday: "April 6",
    gooddistance2: "Medium",
   okdistance2: "Mile/Sprint",
   worstdistance2: "Long",
   goodpace: "Pace/Late",
   okpace: "Front",
   worstpace: "End",
   pollEmbed:[ `<div class="strawpoll-embed" id="strawpoll_05ZdzE0jbn6" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_05ZdzE0jbn6" src="https://strawpoll.com/embed/05ZdzE0jbn6" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>`,
   '<div class="strawpoll-embed" id="strawpoll_7rnzVWXQlnO" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_7rnzVWXQlnO" src="https://strawpoll.com/embed/7rnzVWXQlnO" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
   '<div class="strawpoll-embed" id="strawpoll_PKgleYXWaZp" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_PKgleYXWaZp" src="https://strawpoll.com/embed/PKgleYXWaZp" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>' ]
  },    

  tachyon: {
    personality: "A brilliant mad scientist with no regard for rules or restrictions—Agnes Tachyon believes that the weaknesses of the flesh are merely obstacles waiting to be conquered by science. Equal parts researcher and runner, she relentlessly chases the upper limits of speed through unorthodox and often hazardous experimentation. Her insatiable thirst for knowledge drives her to conduct extreme, unauthorized trials on living subjects—all in the name of progress. However, her intense focus often comes at a cost: without someone to keep her grounded, she easily neglects basic day-to-day needs in favor of her next discovery.",
    trait1: "Strength: Scientific research, sweets, and tea.",
    trait2: "Weaknesses: Interruptions during experiments and anything bitter.",
    trait3: "Family: The eccentric prodigy of a prestigious racing lineage",
    trait4: "Pre-Race Ritual: Methodically checks temperature, humidity, body temp, weather, and wind direction.",
    trait5: "Secret: Buys most of her clothes online—often in the wrong size, but wears them anyway.",
    speedpriority: "750-800",
    staminapriority: "400-450",
    powerpriority: "550-600",
    gutspriority: "350-400",
   witspriority: "350-400",
   skill1: "Pace Chaser Corners",
   skill2: "Professor of Curvature",
   skill3: "Straightaway Acceleration",
   besttotrain: "Focus on speed,then on power,stamina,guts and wit.",  
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Medium and Long", 
   okdistance: "Mile", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Agnes_Tachyon_%28Icon%29.png&width=300",
   profilename: "Agnes Tachyon",
   profilesubtitle: " 'Princess of Superluminal Speed' ",
   rarity: "★",
   type: "Speed/Power",
   distance: "Medium",
   style: "Pace/Late",
   birthday: "April 13",
   gooddistance2: "Medium",
   okdistance2: "Long",
   worstdistance2: "Mile/Sprint",
   goodpace: "Pace",
   okpace: "Late",
   worstpace: "Front/End",
   pollEmbed:[ '<div class="strawpoll-embed" id="strawpoll_40Zm4erlmga" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_40Zm4erlmga" src="https://strawpoll.com/embed/40Zm4erlmga" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_7rnzVWlLDnO" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_7rnzVWlLDnO" src="https://strawpoll.com/embed/7rnzVWlLDnO" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_e2naXQ4LlyB" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_e2naXQ4LlyB" src="https://strawpoll.com/embed/e2naXQ4LlyB" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
    ]
  },    
  
  biwa: {
    personality: "A sharp-minded intellectual with a burning passion—she wields logic like a blade. A true theorist at heart, she approaches every problem with structured analysis and strategic thought. But she’s not all theory—she insists on turning ideas into action, ensuring her methods are grounded in results. Driven by the challenge of matching her sister Narita Brian’s natural talent, she’s worked tirelessly to sharpen her own skills. She's also known for her close friendship with fellow students Narita Taishin and Winning Ticket.",
    trait1: "Strength: Keeping things tidy and organized. ",
    trait2: "Weaknesses: The rainy season—it throws off her rhythm. ",
    trait3: "Family: Her mother and sister once had identical hairstyles.",
    trait4: "Pre-Race Ritual: Studies her competitors thoroughly, right down to their favorite foods.",
    trait5: "Secret: Can eat a banana in five seconds flat.",
    speedpriority: "800-900",
    staminapriority: "900-1000",
    powerpriority: "500-600",
    gutspriority: "250-350",
   witspriority: "400-500",
   skill1: "Pace Chaser Corners",
   skill2: "Homestretch Haste",
   skill3: "Gourmand",
   besttotrain: "Focus on stamina,then on speed,wits,power and guts.",  
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Medium and Long", 
   okdistance: "Mile", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Biwa_Hayahide_%28Icon%29.png&width=300",
   profilename: "Biwa Hayahide",
   profilesubtitle: " 'Victory Investigator' ",
   rarity: "★★★",
   type: "Stamina/Speed",
   distance: "Medium/Long",
   style: "Pace/Late",
   birthday: "March 10",
   gooddistance2: "Med/Long",
   okdistance2: "Mile",
   worstdistance2: "Sprint",
   goodpace: "Pace",
   okpace: "Late",
   worstpace: "End/Front",
   pollEmbed: ['<div class="strawpoll-embed" id="strawpoll_PKgleYMVoZp" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_PKgleYMVoZp" src="https://strawpoll.com/embed/PKgleYMVoZp" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_Q0Zp7jEVGgM" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_Q0Zp7jEVGgM" src="https://strawpoll.com/embed/Q0Zp7jEVGgM" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_kogjRWxDNg6" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_kogjRWxDNg6" src="https://strawpoll.com/embed/kogjRWxDNg6" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  }, 

    curren:{
    personality: "The very definition of cuteness—she’s a selfie queen with over 3,000,000 followers on Umastagram. From the moment she was born, she instantly recognized her own adorableness and has been conquering hearts ever since. With effortless charm, she’s brought both parents and seniors alike to their knees. Her ultimate goal? To rise to the top of the Twinkle Series and prove to the world that she is the absolute pinnacle of cuteness.",
    trait1: "Strength: Snapping perfect selfies and playing the piano.",
    trait2: "Weaknesses: Pairing snacks with tea—it never quite works out.",
    trait3: "Family: Missed her so dearly that they became staff at Tracen Academy just to stay close.",
    trait4: "Pre-Race Ritual: Checks her horseshoes… then her cuteness, in that exact order.",
    trait5: "Secret: Despite her image, half of her favorite top 10 movies are horror films. ",
    speedpriority: "1000-1200",
    staminapriority: "300-400",
    powerpriority: "600-700",
    gutspriority: "300-400",
   witspriority: "800-900",
   skill1: "Straightaway Acceleration",
   skill2: "Homestretch Haste",
   skill3: "Swinging Maestro",
   besttotrain: "Focus on speed,then on wits,power,stamina and guts.",  
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Sprint.", 
   okdistance: "Mile.", 
   worstdistance: "Medium and Long.", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Curren_Chan_%28Icon%29.png&width=300",
   profilename: "Curren Chan",
   profilesubtitle: " 'Sparkling Girl' ",
   rarity: "★★★",
   type: "Speed/Wits",
   distance: "Sprint",
   style: "Pace/Front",
   birthday: "March 31",
   gooddistance2: "Sprint",
   okdistance2: "Mile",
   worstdistance2: "Medium/Long",
   goodpace: "Pace",
   okpace: "Front",
   worstpace: "Late/End",
   pollEmbed:  ['<div class="strawpoll-embed" id="strawpoll_B2ZB9wYrAgJ" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_B2ZB9wYrAgJ" src="https://strawpoll.com/embed/B2ZB9wYrAgJ" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_61gD9XlrOZw" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_61gD9XlrOZw" src="https://strawpoll.com/embed/61gD9XlrOZw" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_eNg6vmKB0gA" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_eNg6vmKB0gA" src="https://strawpoll.com/embed/eNg6vmKB0gA" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

  scarlet: {
      personality: "Unyielding, strong-willed, and just a little cheeky—she aims to be number one in everything she does. Outwardly, she often plays the part of the perfect, mild-mannered honor student, but underneath it all, she despises losing more than anything else. If it means reaching the top, she’s willing to endure any training, no matter how demanding. Her flashy roommate, Vodka, serves as both her greatest motivation and her fiercest rival.",
    trait1: "Strength: Studying and housework.",
    trait2: "Weaknesses: Compromising—she struggles to bend once her mind is set.",
    trait3: "Family: Misses her mother, who pours all her passion into her work.",
    trait4: "Pre-Race Ritual: Requests her trainer to walk behind her for support and focus.",
    trait5: "Secret: Secretly sends fan letters to her favorite manga authors",
    speedpriority: "800-900",
    staminapriority: "500-600",
    powerpriority: "500-600",
    gutspriority: "200-300",
   witspriority: "300-400",
   skill1: "Focus",
   skill2: "Up-Tempo",
   skill3: "Killer Tunes",
   besttotrain: "Focus on speed,then on stamina,power,wits and guts.",  
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Mile and Medium", 
   okdistance: "Long", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Daiwa_Scarlet_%28Icon%29.png&width=300",
   profilename: "Daiwa Scarlet",
   profilesubtitle: " 'Miss Perfect' ",
   rarity: "★★",
   type: "Speed/Stamina",
   distance: "Mile/Medium",
   style: "Front/Pace",
   birthday: "May 13",
   gooddistance2: "Mile/Med",
   okdistance2: "Long",
   worstdistance2: "Sprint",
   goodpace: "Front/Pace",
   okpace: "Late",
   worstpace: "End",
   pollEmbed:  ['<div class="strawpoll-embed" id="strawpoll_ajnE1XpmxnW" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_ajnE1XpmxnW" src="https://strawpoll.com/embed/ajnE1XpmxnW" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_40Zm4evLlga" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_40Zm4evLlga" src="https://strawpoll.com/embed/40Zm4evLlga" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_7rnzVWE2LnO" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_7rnzVWE2LnO" src="https://strawpoll.com/embed/7rnzVWE2LnO" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

   elcondor: {
      personality: "A masked luchadora brimming with energy—she’s always hyped and ready to fight! With unshakable confidence, she proudly declares herself the strongest Umamusume in the world, and she’ll announce it to anyone willing to listen. Her mask, a precious gift from her pro-wrestler father, never leaves her face; she insists on wearing it at all times, no exceptions. Though her reckless behavior often earns her scolding from her best friend and roommate, Grass Wonder, her spirit never wavers.",
    trait1: "Strength: Professional wrestling techniques.",
    trait2: "Weaknesses: Staying quiet—silence just isn’t her style.",
    trait3: "Family: Grew up alongside a hawk named Mambo, whom she treats like a sibling.",
    trait4: "Pre-Race Ritual: Dramatically throws her jacket to the ground—then calmly picks it back up.",
    trait5: "Secret: Extremely ticklish, though she tries to hide it.",
    speedpriority: "900-1000",
    staminapriority: "200-300",
    powerpriority: "600-700",
    gutspriority: "200-300",
   witspriority: "400-500",
   skill1: "Professor of Curvature",
   skill2: "Straightaway Acceleration",
   skill3: "Homestretch Haste",
   besttotrain: "Focus on speed,then on power,wits,stamina and guts.",  
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Mile and Medium", 
   okdistance: "Long", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=El_Condor_Pasa_%28Icon%29.png&width=340",
   profilename: "El Condor Pasa",
   profilesubtitle: " 'Mysterious Bird' ",
   rarity: "★★",
   type: "Speed/Power",
   distance: "Mile/Medium",
   style: "Pace/Late",
   birthday: "March 17",
   gooddistance2: "Mile/Med",
   okdistance2: "Long",
   worstdistance2: "Sprint",
   goodpace: "Pace/Late",
   okpace: "End",
   worstpace: "Front",
   pollEmbed:  ['<div class="strawpoll-embed" id="strawpoll_GPgVYQK8Ena" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_GPgVYQK8Ena" src="https://strawpoll.com/embed/GPgVYQK8Ena" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_GeZAR4qwJyV" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_GeZAR4qwJyV" src="https://strawpoll.com/embed/GeZAR4qwJyV" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_7MZ0kGqaKgo" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_7MZ0kGqaKgo" src="https://strawpoll.com/embed/7MZ0kGqaKgo" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

goldship:{
      personality: "Wild, free-spirited, and utterly unpredictable—this golden runner is unlike anyone else! A mischievous firebrand through and through, her moods and motivation shift like the wind. One moment she’s setting up an elaborate joke, and the next she’s impossible to move from her spot. Though she seems friendly with just about everyone, the true nature of how she views her bonds is shrouded in mystery. Among the halls of Tracen, she’s known as the academy’s greatest mischief-maker.",
    trait1: "Strength: Highly expressive facial movements.",
    trait2: "Weaknesses: Staying still for any length of time.",
    trait3: "Family: Treated as if they’re some kind of national secret.",
    trait4: "Pre-Race Ritual: Enters the starting gate full of fiery bravado, “guns blazing”.",
    trait5: "Secret: Scarily good at trivia games.",
    speedpriority: "500-550",
    staminapriority: "550-600",
    powerpriority: "550-600",
    gutspriority: "270-300",
   witspriority: "300",
   skill1: "Straightaway Acceleration",
   skill2: "Homestretch Haste",
   skill3: "Nimble Navigator",
   besttotrain: "Focus on stamina,then on power,speed,wits and guts.",
   racestrategy: "Mostly pick End on any distance. Late and Pace can also work.", 
   bestdistance: "Long and Medium", 
   okdistance: "Mile", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Gold_Ship_%28Icon%29.png&width=300",
   profilename: "Gold Ship",
   profilesubtitle: " 'Unprecedented' ",
   rarity: "★★",
   type: "Stamina/Power",
   distance: "Long/Medium",
   style: "End",
   birthday: "March 6",
   gooddistance2: "Med/Long",
   okdistance2: "Mile",
   worstdistance2: "Sprint",
   goodpace: "End",
   okpace: "Pace/Late",
   worstpace: "Front",
   pollEmbed:  ['<div class="strawpoll-embed" id="strawpoll_X3nkP72RzgE" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_X3nkP72RzgE" src="https://strawpoll.com/embed/X3nkP72RzgE" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_40Zm4e7DKga" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_40Zm4e7DKga" src="https://strawpoll.com/embed/40Zm4e7DKga" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_e2naXQK0wyB" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_e2naXQK0wyB" src="https://strawpoll.com/embed/e2naXQK0wyB" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

  grasswonder: {
      personality: "Neat, sweet, and proudly Japanese at heart—she’s returned home after living in the U.S. Though born abroad, her parents’ deep love for Japanese culture shaped her into someone who treasures tradition to the fullest. So much so, in fact, that many consider her the very picture of an ideal Japanese beauty. Warm and approachable in conversation yet unshakable in will, her determination to win rivals anyone’s. She shares her dorm with her dear friend, El Condor Pasa.",
    trait1: "Strength: Japanese sweets, traditional culture, and competitive karuta. ",
    trait2: "Weaknesses: Insects, and any slight against history or tradition.",
    trait3: "Family: “My parents inspired my love for Japan—they even keep a full Japanese-style room in our house.”",
    trait4: "Pre-Race Ritual: Recites the names of every runner in the race by memory.",
    trait5: "Secret: Can’t decide whether a matcha latte truly counts as a Japanese drink.",
    speedpriority: "900-1000",
    staminapriority: "400-500",
    powerpriority: "500-600",
    gutspriority: "200-300",
   witspriority: "400-500",
   skill1: "Go with the Flow",
   skill2: "Corner Adept ◯",
   skill3: "Straightaway Acceleration",
   besttotrain: "Focus on speed,then on power,stamina,wits and guts.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Mile and Long.", 
   okdistance: "Medium", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Grass_Wonder_%28Icon%29.png&width=300",
   profilename: "Grass Wonder",
   profilesubtitle: " 'Phoenix' ",
   rarity: "★★",
   type: "Speed/Power",
   distance: "Mile/Long",
   style: "Pace/Late",
   birthday: "February 18",
   gooddistance2: "Mile/Long",
   okdistance2: "Medium",
   worstdistance2: "Sprint",
   goodpace: "Pace/Late",
   okpace: "",
   worstpace: "Front/End",
   pollEmbed:  ['<div class="strawpoll-embed" id="strawpoll_LVyK2LKO7Z0" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_LVyK2LKO7Z0" src="https://strawpoll.com/embed/LVyK2LKO7Z0" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_w4nWWVKxdnA" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_w4nWWVKxdnA" src="https://strawpoll.com/embed/w4nWWVKxdnA" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_3RnYX6KMBye" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_3RnYX6KMBye" src="https://strawpoll.com/embed/3RnYX6KMBye" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

  haru: {
      personality: "No matter how many times she stumbles, she always gets back on her feet! Currently stuck in a losing streak, she refuses to give up. Though her skills may not be the sharpest, she fell in love with the thrill of racing back in Kochi—and ever since, her passion has only grown. Despite completely failing Tracen Academy’s entrance exam, her admissions officer saw in her an undeniable spark of possibility. That boundless energy now inspires everyone around her.",
    trait1: "Strength: Throwing herself into things with all her might.",
    trait2: "Weaknesses: Struggles with difficult kanji.",
    trait3: "Family: Loves her mother’s homemade carrot rice the most.",
    trait4: "Pre-Race Ritual: Simply gets herself hyped up—“Get excited~♪”.",
    trait5: "Secret: Shockingly good at catching dragonflies with her bare hands.",
    speedpriority: "650-700",
    staminapriority: "400-450",
    powerpriority: "550-580",
    gutspriority: "330-350",
   witspriority: "300-350",
   skill1: "Slick Surge",
   skill2: "Nimble Navigator",
   skill3: "Swinging Maestro",
   besttotrain: "Focus on speed,then on power,stamina,guts and wits.",
   racestrategy: "On Sprint choose End. On Mile choose Late. On Medium choose Pace. On Long choose Front.", 
   bestdistance: "Sprint", 
   okdistance: "Mile", 
   worstdistance: "Medium and Long", 
   track: "She performs best on dirt tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Haru_Urara_%28Icon%29.png&width=300",
   profilename: "Haru Urara",
   profilesubtitle: " 'Persistent Haru Urara' ",
   rarity: "★",
   type: "Speed/Power",
   distance: "Sprint/Mile",
   style: "Late/End",
   birthday: "February 27",
   gooddistance2: "Sprint",
   okdistance2: "Mile",
   worstdistance2: "Med/Long",
   goodpace: "Late",
   okpace: "End",
   worstpace: "Pace/Front",
   pollEmbed:  ['<div class="strawpoll-embed" id="strawpoll_1Mnwkzodjn7" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_1Mnwkzodjn7" src="https://strawpoll.com/embed/1Mnwkzodjn7" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_YVyPvXK59gN" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_YVyPvXK59gN" src="https://strawpoll.com/embed/YVyPvXK59gN" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_wAg3QOR4dy8" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_wAg3QOR4dy8" src="https://strawpoll.com/embed/wAg3QOR4dy8" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

  halo: {
      personality: "Haughty, dazzling, and proud enough to touch the heavens—King Halo carries herself with the unshakable spirit of nobility. Determined to prove herself a true first-class lady, she faces every challenge head-on in pursuit of recognition. Though her relationship with her mother—a celebrated Umamusume and renowned designer—remains strained, she strives to one day earn her approval as both a rival and a daughter. Yet within Tracen Academy, her loyal admirers already hail her as their “King,” and in their eyes, she is second to none.",
    trait1: "Strength: Skilled in design and fashion.",
    trait2: "Weaknesses: Crowds, heat, and other “unworthy” conditions for someone of her class.",
    trait3: "Family: Her mother is hopeless at housework, so servants manage the household.",
    trait4: "Pre-Race Ritual: Sounds her unmistakable King’s Call before heading off.",
    trait5: "Secret: Talks back to the screen while watching dramas, often clicking her tongue with a “tsk, tsk”.",
    speedpriority: "900-1000",
    staminapriority: "300-400",
    powerpriority: "500-600",
    gutspriority: "300-400",
   witspriority: "300-400",
   skill1: "Straightaway Acceleration",
   skill2: "Homestretch Haste",
   skill3: "Straightaway Adept",
   besttotrain: "Focus on speed,then on power,stamina,guts and wits.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Sprint", 
   okdistance: "Mile and Medium", 
   worstdistance: "Long", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=King_Halo_%28Icon%29.png&width=300",
   profilename: "King Halo",
   profilesubtitle: " 'King of the World' ",
   rarity: "★",
   type: "Speed/Power",
   distance: "Sprint",
   style: "Late",
   birthday: "April 28",
   gooddistance2: "Sprint",
   okdistance2: "Mile/Med",
   worstdistance2: "Long",
   goodpace: "Late",
   okpace: "Pace",
   worstpace: "End/Front",
   pollEmbed:  ['<div class="strawpoll-embed" id="strawpoll_w4nWWVN25nA" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_w4nWWVN25nA" src="https://strawpoll.com/embed/w4nWWVN25nA" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_QrgewJ6vryp" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_QrgewJ6vryp" src="https://strawpoll.com/embed/QrgewJ6vryp" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_PKgleYa89Zp" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_PKgleYa89Zp" src="https://strawpoll.com/embed/PKgleYa89Zp" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]

  },

  maruzensky: {
      personality: "Keeping it old-school and full of flair—she’s a true hot rod at heart! With a sisterly demeanor and a charmingly retro way of speaking, she lives for the pure thrill of speed. On the road, her father’s second-hand red supercar burns rubber, but on the track, it’s all her own legs tearing through the finish line. Despite her raw power and talent, she remains humble and is adored by everyone around her.",
    trait1: "Strength: Expert at drifting.",
    trait2: "Weaknesses: Driving—or running—too slowly.",
    trait3: "Family: Drives her father’s cherished second-hand red supercar.",
    trait4: "Pre-Race Ritual: Chats casually with competitors before racing.",
    trait5: "Secret: Gets car sick as a passenger.",
    speedpriority: "900-1000",
    staminapriority: "600-700",
    powerpriority: "500-600",
    gutspriority: "300-400",
   witspriority: "400-500",
   skill1: "Professor of Curvature",
   skill2: "Straightaway Acceleration",
   skill3: "Homestretch Haste",
   besttotrain: "Focus on speed,then on stamina,power,wits and guts.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Mile", 
   okdistance: "Med/Sprint", 
   worstdistance: "Long", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Maruzensky_%28Icon%29.png&width=300",
   profilename: "Maruzensky",
   profilesubtitle: " 'Supercar' ",
   rarity: "★★★",
   type: "Speed/Stamina",
   distance: "Mile",
   style: "Front",
   birthday: "May 19",
   gooddistance2: "Mile",
   okdistance2: "Med/Sprint",
   worstdistance2: "Long",
   goodpace: "Front",
   okpace: "Pace",
   worstpace: "Late/End",
   pollEmbed:  ['<div class="strawpoll-embed" id="strawpoll_e2naXQ15pyB" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_e2naXQ15pyB" src="https://strawpoll.com/embed/e2naXQ15pyB" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_3RnYX6P7Qye" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_3RnYX6P7Qye" src="https://strawpoll.com/embed/3RnYX6P7Qye" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_QrgewJ6vOyp" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_QrgewJ6vOyp" src="https://strawpoll.com/embed/QrgewJ6vOyp" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

matikane: {
      personality: "This charm-tastic Umamusume adores fortune-telling and finds joy in leaving things up to fate. Whether it’s a race or a simple daily choice, she believes destiny guides the way. If she isn’t divining her own future, she’s happily predicting fortunes for others.She places immense faith in a revelation from a certain god: “As long as you keep running, the way forward will open before you.” With this belief in her heart—and her beloved cat-shaped bag “Miss Nya” always at her side—she strides forward with confidence.",
    trait1: "Strength: Fortune-telling.",
    trait2: "Weaknesses: Unlucky things.",
    trait3: "Family: Looks up to her younger sister’s cheerful nature, admiring her like an excellent older sibling.",
    trait4: "Pre-Race Ritual: Offers a prayer to Shiraoki-sama for victory!!",
    trait5: "Secret: Holds an advanced rank in calligraphy.",
    speedpriority: "800-900",
    staminapriority: "800-900",
    powerpriority: "400-500",
    gutspriority: "200-300",
   witspriority: "300-400",
   skill1: "Go with the Flow",
   skill2: "Professor of Curvature",
   skill3: "Homestretch Haste",
   besttotrain: "Focus on speed,then on stamina,power,wits and guts.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Med/Long", 
   okdistance: "Mile", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Matikanefukukitaru_%28Icon%29.png&width=300",
   profilename: "Matikanefukukitaru",
   profilesubtitle: " 'Fortune Comes to Those who Smile' ",
   rarity: "★",
   type: "Speed/Stamina",
   distance: "Med/Long",
   style: "Late",
   birthday: "May 22",
   gooddistance2: "Med/Long",
   okdistance2: "Mile",
   worstdistance2: "Sprint",
   goodpace: "Late",
   okpace: "Pace",
   worstpace: "End/Front",
   pollEmbed:  ['<div class="strawpoll-embed" id="strawpoll_jVyG2XmQ8Z7" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_jVyG2XmQ8Z7" src="https://strawpoll.com/embed/jVyG2XmQ8Z7" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_6QnMQXYx8ne" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_6QnMQXYx8ne" src="https://strawpoll.com/embed/6QnMQXYx8ne" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_NoZrzwlGeZ3" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_NoZrzwlGeZ3" src="https://strawpoll.com/embed/NoZrzwlGeZ3" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

  mayano: {
      personality: "She’s like your sweet little sister—bright, playful, and bursting with energy! Mayano Top Gun dreams of becoming a refined, mature lady, but her boundless curiosity and childlike excitement often get the better of her. With a pilot for a father, aviation terms slip naturally into her speech, and she’s always ready to “lock on” to her next source of fun. Despite her scatterbrained enthusiasm, she has an uncanny intuition and a knack for knowing just what to do in the moment.",
    trait1: "Strength: Almost everything she sets her mind to!",
    trait2: "Weaknesses: Terrible at hiding things—her emotions (and tail!) always give her away.",
    trait3: "Family: Her dad was a pilot, so the airport became her childhood playground.",
    trait4: "Pre-Race Ritual: She always locks onto Trainer’s seat in the audience—target acquired!",
    trait5: "Secret: Can fold amazing paper airplanes out of any scrap of paper.",
    speedpriority: "900-1000",
    staminapriority: "700-800",
    powerpriority: "700-800",
    gutspriority: "200-300",
   witspriority: "200-300",
   skill1: "Go with the Flow",
   skill2: "Professor of Curvature",
   skill3: "Straightaway Acceleration",
   besttotrain: "Focus on speed,then on stamina,power,wits and guts.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Med/Long", 
   okdistance: "Mile/Sprint", 
   worstdistance: "-", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Mayano_Top_Gun_%28Icon%29.png&width=300",
   profilename: "Mayano Top Gun",
   profilesubtitle: " 'Shapeshifter' ",
   rarity: "★★",
   type: "Speed/Stamina",
   distance: "Med/Long",
   style: "Front/Pace",
   birthday: "March 24",
   gooddistance2: "Med/Long",
   okdistance2: "Mile/Sprint",
   worstdistance2: "-",
   goodpace: "Front/Pace",
   okpace: "Late/End",
   worstpace: "-",
   pollEmbed:  ['<div class="strawpoll-embed" id="strawpoll_7MZ0kGVx8go" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_7MZ0kGVx8go" src="https://strawpoll.com/embed/7MZ0kGVx8go" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_XOgOVblpQn3" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_XOgOVblpQn3" src="https://strawpoll.com/embed/XOgOVblpQn3" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_3RnYX6PGmye" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_3RnYX6PGmye" src="https://strawpoll.com/embed/3RnYX6PGmye" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

  mcqueen: {
    personality: "The crown jewel of the prestigious Mejiro clan, she is the very picture of class and poise. Born into a family of racing legends, Mejiro McQueen has long-distance talent that inspires admiration from all her peers. Determined to uphold her family’s legacy, she aims to claim first place at the Tenno Sho, just like the Mejiro racers before her. On her days off, she enjoys refined pleasures like afternoon tea with the other residents of the Mejiro estate.",
    trait1: "Strength: Perfect table manners and impeccable etiquette.",
    trait2: "Weaknesses: Struggles to resist sweets.",
    trait3: "Family: Affectionately called “Mac-chan” by her parents.",
    trait4: "Pre-Race Ritual: Checks her temperature with a thermometer, a habit since childhood.",
    trait5: "Secret: Has woken herself up in the night yelling, “Let’s kick some ass!”",
    speedpriority: "700-800",
    staminapriority: "500-600",
    powerpriority: "300-400",
    gutspriority: "300-400",
   witspriority: "200-300",
   skill1: "Pace Chaser Corners ◯",
   skill2: "Professor of Curvature",
   skill3: "Homestretch Haste",
   besttotrain: "Focus on speed,then on stamina,power,guts and wits.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Med/Long", 
   okdistance: "-", 
   worstdistance: "Mile/Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Mejiro_McQueen_%28Icon%29.png&width=300",
   profilename: "Mejiro McQueen",
   profilesubtitle: " 'Famous Actress' ",
   rarity: "★★★",
   type: "Speed/Stamina",
   distance: "Med/Long",
   style: "Pace",
   birthday: "April 3",
   gooddistance2: "Med/Long",
   okdistance2: "-",
   worstdistance2: "Mile/Sprint",
   goodpace: "Pace",
   okpace: "Front/Late",
   worstpace: "End",
   pollEmbed:  ['<div class="strawpoll-embed" id="strawpoll_jVyG2XmzGZ7" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_jVyG2XmzGZ7" src="https://strawpoll.com/embed/jVyG2XmzGZ7" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_61gD9XOEOZw" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_61gD9XOEOZw" src="https://strawpoll.com/embed/61gD9XOEOZw" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_eNg6vmV10gA" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_eNg6vmV10gA" src="https://strawpoll.com/embed/eNg6vmV10gA" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },
  narita: {
      personality: "A cold and formidable runner whose speed leaves both awe and fear in her wake. At Tracen Academy, her very presence inspires respect, if not dread. She runs for no one but herself, chasing only the thirst within. Despite her stern demeanor, she is the younger sister of Biwa Hayahide and serves, somewhat surprisingly, as the vice president of the student council.",
    trait1: "Strength: Crushing walnuts with ease.",
    trait2: "Weaknesses: Anything small and delicate.",
    trait3: "Family: Her parents and sister insist her silence is a form of kindness.",
    trait4: "Pre-Race Ritual: Reapplies the tape on her nose.",
    trait5: "Secret: The stem she always carries is homegrown.",
    speedpriority: "800-900",
    staminapriority: "800-900",
    powerpriority: "600-700",
    gutspriority: "200-300",
   witspriority: "300-400",
   skill1: "Professor of Curvature",
   skill2: "Prepared to Pass",
   skill3: "Homestretch Haste",
   besttotrain: "Focus on speed,then on stamina,power,wits and guts.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Med/Long", 
   okdistance: "Mile", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Narita_Brian_%28Icon%29.png&width=300",
   profilename: "Narita Brian",
   profilesubtitle: " 'A Monster that Fears no Shadow' ",
   rarity: "★★★",
   type: "Speed/Stamina",
   distance: "Med/Long",
   style: "Pace/Late",
   birthday: "May 3",
   gooddistance2: "Med/Long",
   okdistance2: "Mile",
   worstdistance2: "Sprint",
   goodpace: "Pace/Late",
   okpace: "End",
   worstpace: "Front",
   pollEmbed: ['<div class="strawpoll-embed" id="strawpoll_PbZqb42jByN" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_PbZqb42jByN" src="https://strawpoll.com/embed/PbZqb42jByN" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_GPgVYQABvna" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_GPgVYQABvna" src="https://strawpoll.com/embed/GPgVYQABvna" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_XmZRQXARWgd" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_XmZRQXARWgd" src="https://strawpoll.com/embed/XmZRQXARWgd" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

  ryan: {
      personality: "A sporty girl from the prestigious Mejiro family, though her lively personality makes her stand out. Despite her physical strength, she carries a delicate heart and a quiet inferiority complex toward her childhood friend, Mejiro McQueen. She dreams of being just as fast and beautiful one day.",
    trait1: "Strength:  Muscle training champ.",
    trait2: "Weaknesses: Cholesterol woes.",
    trait3: "Family: Young-looking dad often mistaken for her brother.",
    trait4: "Pre-Race Ritual: Pumps herself up with: “My muscles are the strongest!”",
    trait5: "Secret: Can’t resist trying on clothes before buying.",
    speedpriority: "900-1000",
    staminapriority: "500-600",
    powerpriority: "700-800",
    gutspriority: "200-300",
   witspriority: "200-300",
   skill1: "Corner Adept ◯",
   skill2: "Professor of Curvature",
   skill3: "Straightaway Acceleration",
   besttotrain: "Focus on speed,then on power,stamina,guts and wits.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Medium", 
   okdistance: "Long/Mile", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Mejiro_Ryan_%28Icon%29.png&width=300",
   profilename: "Mejiro Ryan",
   profilesubtitle: " 'A Lovely and Influential Person' ",
   rarity: "★",
   type: "Speed",
   distance: "Medium",
   style: "Pace/Late",
   birthday: "April 11",
   gooddistance2: "Medium",
   okdistance2: "Long/Mile",
   worstdistance2: "Sprint",
   goodpace: "Pace/Late",
   okpace: "-",
   worstpace: "Front/End",
   pollEmbed: ['<div class="strawpoll-embed" id="strawpoll_NPgxeajbPZ2" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_NPgxeajbPZ2" src="https://strawpoll.com/embed/NPgxeajbPZ2" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_poy9k20X2gJ" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_poy9k20X2gJ" src="https://strawpoll.com/embed/poy9k20X2gJ" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_kjn1D90ddyQ" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_kjn1D90ddyQ" src="https://strawpoll.com/embed/kjn1D90ddyQ" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

 bourbon: {
    personality: "Nicknamed the Cyborg, she approaches life with machine-like precision, relying on programming-like logic and data to guide her decisions. Calm, expressionless, and efficient, she always carries out her objectives with flawless execution. Though her exterior may seem cold, it is simply the result of endless years of rigorous training that left her little time for ordinary interactions. Beneath the robotic façade, however, rests a heart with emotions she seldom shows.",
    trait1: "Strength: Staring (her unblinking gaze can unnerve opponents and focus her own willpower).",
    trait2: "Weaknesses: Operating electrical appliances (she tends to break them unintentionally).",
    trait3: "Family: Lives in an old-fashioned home, as their household appliances frequently short out around her.",
    trait4: "Pre-Race Ritual: Measures humidity, temperature, and wind direction directly with her own senses, adjusting strategy with machine-like precision.",
    trait5: "Secret: Thanks to her father’s constant teasing, she still half-believes her tail could be struck by lightning.",
    speedpriority: "700-800",
    staminapriority: "300-400",
    powerpriority: "500-600",
    gutspriority: "200-300",
   witspriority: "300-400",
   skill1: "Focus",
   skill2: "Final Push",
   skill3: "Straightaway Acceleration",
   besttotrain: "Focus on speed,then on power,stamina,wits and guts.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Medium", 
   okdistance: "Mile/Long", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Mihono_Bourbon_%28Icon%29.png&width=300",
   profilename: "Mihono Bourbon",
   profilesubtitle: " 'Child of the Slope' ",
   rarity: "★★★",
   type: "Speed",
   distance: "Medium",
   style: "Front",
   birthday: "April 25",
   gooddistance2: "Medium",
   okdistance2: "Mile/Long",
   worstdistance2: "Sprint",
   goodpace: "Front",
   okpace: "-",
   worstpace: "Pace/Late/End",
   pollEmbed: ['<div class="strawpoll-embed" id="strawpoll_7rnzVWwJanO" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_7rnzVWwJanO" src="https://strawpoll.com/embed/7rnzVWwJanO" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_e6Z2AB0JXgN" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_e6Z2AB0JXgN" src="https://strawpoll.com/embed/e6Z2AB0JXgN" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_w4nWWVAmQnA" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_w4nWWVAmQnA" src="https://strawpoll.com/embed/w4nWWVAmQnA" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

  taishin: {
      personality: "Despite her slight frame, she carries an unexpected edge on the track. A rebellious and sharp-minded Umamusume, she was often teased for her small stature—an experience that fuels her determination to prove her abilities. Her blunt, no-nonsense demeanor reflects her disdain for being underestimated. She is close friends with Winning Ticket and Biwa Hayahide.",
    trait1: "Strength: Video games, housework.",
    trait2: "Weaknesses: Crowds and bustling environments.",
    trait3: "Family: Rumor has it the mothers of the BNW trio are friends now.",
    trait4: "Pre-Race Ritual: Keeps a low profile before the start.",
    trait5: "Secret: Addicted to solo-camping videos.",
    speedpriority: "900-1000",
    staminapriority: "500-600",
    powerpriority: "600-700",
    gutspriority: "200-300",
   witspriority: "400-500",
   skill1: "Professor of Curvature",
   skill2: "Homestretch Haste",
   skill3: "Cooldown",
   besttotrain: "Focus on speed,then on power,stamina,wits and guts.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Med/Long", 
   okdistance: "Mile", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Narita_Taishin_%28Icon%29.png&width=300",
   profilename: "Narita Taishin",
   profilesubtitle: " 'Reversal Umamusume' ",
   rarity: "★★★",
   type: "Speed",
   distance: "Med/Long",
   style: "End",
   birthday: "June 10",
   gooddistance2: "Med/Long",
   okdistance2: "Mile",
   worstdistance2: "Sprint",
   goodpace: "End",
   okpace: "Late",
   worstpace: "Pace/Front",
   pollEmbed: ['<div class="strawpoll-embed" id="strawpoll_ajnE1X0jxnW" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_ajnE1X0jxnW" src="https://strawpoll.com/embed/ajnE1X0jxnW" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_40Zm4eJ3lga" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_40Zm4eJ3lga" src="https://strawpoll.com/embed/40Zm4eJ3lga" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_e2naXQAp0yB" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_e2naXQAp0yB" src="https://strawpoll.com/embed/e2naXQAp0yB" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

  nature: {
      personality: "Born into a modest family, she leans toward pessimism and rarely sees herself as the “main character.” Because of this, she often avoids big expectations, which can sometimes lead to less-than-perfect results. Thanks to her working-class upbringing, she’s skilled at household tasks like cooking and cleaning, and often puts those skills to use in her spare time. Among the seniors in her hometown, she’s a well-known and familiar presence.",
    trait1: "Strength: Ping pong, hunting down delicious snacks.",
    trait2: "Weaknesses: Social media (SNS)",
    trait3: "Family: Her family’s bar proudly displays articles written about her on its walls.",
    trait4: "Pre-Race Ritual: She unconsciously fluffs up her hair.",
    trait5: "Secret: A master at managing fridge leftovers.",
    speedpriority: "600-700",
    staminapriority: "550-600",
    powerpriority: "550-650",
    gutspriority: "250-300",
   witspriority: "300-350",
   skill1: "Go with the Flow",
   skill2: "Professor of Curvature",
   skill3: "Homestretch Haste",
   besttotrain: "Focus on speed,then on power,stamina,wits and guts.",
   racestrategy: "On Sprint choose End. On Mile choose Late. On Medium choose Pace. On Long choose Front.", 
   bestdistance: "Med/Long", 
   okdistance: "Mile", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Nice_Nature_%28Icon%29.png&width=300",
   profilename: "Nice Nature",
   profilesubtitle: " 'The Loveable Supporting Character' ",
   rarity: "★",
   type: "Speed/Power",
   distance: "Med/Long",
   style: "Late",
   birthday: "April 16",
   gooddistance2: "Med/Long",
   okdistance2: "Mile",
   worstdistance2: "Sprint",
   goodpace: "Late",
   okpace: "Pace/End",
   worstpace: "Front",
   pollEmbed: ['<div class="strawpoll-embed" id="strawpoll_Q0Zp7ja8jgM" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_Q0Zp7ja8jgM" src="https://strawpoll.com/embed/Q0Zp7ja8jgM" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_GJn44E0Mznz" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_GJn44E0Mznz" src="https://strawpoll.com/embed/GJn44E0Mznz" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_1MnwkzpaAn7" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_1MnwkzpaAn7" src="https://strawpoll.com/embed/1MnwkzpaAn7" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

  oguri: {
      personality: "Born and raised far from the bustle of the city, she made a name for herself in her hometown’s racing scene before earning her place at Tracen Academy. Though determined to make her people proud, her clumsy streak always manages to peek through. On campus, she’s most famous for her legendary appetite—able to polish off a full pot of rice in an instant.",
    trait1: "Strength: Eating (bottomless stomach, lightning speed).",
    trait2: "Weaknesses: Swimming (she sinks like a stone).",
    trait3: "Family: Fond memories of hot spring trips; she’s a regular at a hidden inn.",
    trait4: "Pre-Race Ritual: She recalls the smiles of everyone who’s supported her.",
    trait5: "Secret: Her dream is to one day become doteyaki (a hearty beef stew).",
    speedpriority: "1000-1100",
    staminapriority: "300-400",
    powerpriority: "500-600",
    gutspriority: "200-300",
   witspriority: "300-400",
   skill1: "Go with the Flow",
   skill2: "Homestretch Haste",
   skill3: "Gourmand",
   besttotrain: "Focus on speed,then on power,stamina,wits and guts.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Mile/Med", 
   okdistance: "Long", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Oguri_Cap_%28Icon%29.png&width=300",
   profilename: "Oguri Cap",
   profilesubtitle: " 'Idol Umamusume' ",
   rarity: "★★★",
   type: "Speed",
   distance: "Mile/Med",
   style: "Pace/Late",
   birthday: "March 27",
   gooddistance2: "Mile/Med",
   okdistance2: "Long",
   worstdistance2: "Sprint",
   goodpace: "Pace/Late",
   okpace: "End",
   worstpace: "Front",
   pollEmbed: ['<div class="strawpoll-embed" id="strawpoll_LVyK2LkmKZ0" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_LVyK2LkmKZ0" src="https://strawpoll.com/embed/LVyK2LkmKZ0" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_X3nkP7wJzgE" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_X3nkP7wJzgE" src="https://strawpoll.com/embed/X3nkP7wJzgE" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>',
    '<div class="strawpoll-embed" id="strawpoll_e7ZJaXvJvg3" style="height: 400px; max-width: 420px; width: 100%; margin: 0 auto; display: flex; flex-direction: column;"><iframe title="StrawPoll Embed" id="strawpoll_iframe_e7ZJaXvJvg3" src="https://strawpoll.com/embed/e7ZJaXvJvg3" style="position: static; visibility: visible; display: block; width: 100%; flex-grow: 1;" frameborder="0" allowfullscreen allowtransparency>Loading...</iframe><script async src="https://cdn.strawpoll.com/dist/widgets.js" charset="utf-8"></script></div>'
   ]
  },

  riceshower: {
      personality: "A shy and timid Umamusume, she believes that any bad luck affecting those around her is her fault—though in reality, it’s usually just poor timing. Still, she is determined to overcome this self-perceived jinx. In her free time, she enjoys reading picture books, with a particular fondness for “The Blue Rose of Good Fortune.”",
    trait1: "Strength: Drawing.",
    trait2: "Weaknesses: Others’ misfortune, ghosts.",
    trait3: "Family: Grew up falling asleep to her parents reading picture books aloud.",
    trait4: "Pre-Race Ritual: Spends extra time stretching to prepare her body.",
    trait5: "Secret: Prefers bread over rice for breakfast; dreams of owning a complete set of 500 colored pencils.",
    speedpriority: "500-550",
    staminapriority: "600-700",
    powerpriority: "450-500",
    gutspriority: "350-400",
   witspriority: "300",
   skill1: "Pace Chaser Corners ◯",
   skill2: "Professor of Curvature",
   skill3: "Homestretch Haste",
   besttotrain: "Focus on stamina,then on speed,power,guts and wits.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Med/Long", 
   okdistance: "Mile", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Rice_Shower_%28Icon%29.png&width=300",
   profilename: "Rice Shower",
   profilesubtitle: " 'Black Assassin' ",
   rarity: "★★★",
   type: "Stamina",
   distance: "Med/Long",
   style: "Pace",
   birthday: "March 5",
   gooddistance2: "Med/Long",
   okdistance2: "Mile",
   worstdistance2: "Sprint",
   goodpace: "Pace",
   okpace: "Front/Late",
   worstpace: "End",
   pollEmbed: ['',
    '',
    ''
   ]
  },

  bakushin: {
      personality: "A determined class representative who barrels headfirst into any situation. Once she sets her mind on a goal, she dashes straight toward it—sometimes creating more chaos than she solves. Despite her reckless energy, she never acts out of arrogance, and can feel disheartened if no one seeks her help. Her sprinting ability is exceptional, giving her confidence that she can outrun anyone.",
    trait1: "Strength: Being dependable, helping others.",
    trait2: "Weaknesses: Tasks that require more than three steps.",
    trait3: "Family: Raised with the motto: “Praise, praise, praise, and praise!”",
    trait4: "Pre-Race Ritual: Calls her sister immediately in response to a supportive message.",
    trait5: "Secret: Skilled at brewing tea; keeps a shogi piece, kyousha, as a lucky charm.",
    speedpriority: "1100-1200",
    staminapriority: "200-300",
    powerpriority: "500-600",
    gutspriority: "200-300",
   witspriority: "400-500",
   skill1: "Straightaway Acceleration",
   skill2: "Homestretch Haste",
   skill3: "Early Lead",
   besttotrain: "Focus on speed,then on power,wits,stamina and guts.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Sprint", 
   okdistance: "Mile", 
   worstdistance: "Med/Long", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Sakura_Bakushin_O_%28Icon%29.png&width=300",
   profilename: "Sakura Bakushin O",
   profilesubtitle: " 'Ruler of Dashing' ",
   rarity: "★",
   type: "Speed",
   distance: "Sprint",
   style: "Front/Pace",
   birthday: "April 14",
   gooddistance2: "Sprint",
   okdistance2: "Mile",
   worstdistance2: "Med/Long",
   goodpace: "Front/Pace",
   okpace: "-",
   worstpace: "Late/End",
   pollEmbed: ['',
    '',
    ''
   ]
  }, 

  falcon: {
    personality: "She’s a self-proclaimed idol racer, known as an Umadol, and she refuses to let anyone else outshine her on stage or on the track. Whether she’s dashing toward the finish line or striking a perfect pose for the crowd, she always keeps one goal in mind: be the cutest, the brightest, and the center of attention.Her fans adore her energy, and she makes sure to return the love—remembering names, faces, and cheering back when she hears their voices. She never misses a chance at an event, photoshoot, or concert that boosts her idol status. While she’s secretly a strong dirt racer, she’s a bit embarrassed by the “messy” side of it, and tries to focus on the glitter, lights, and glam instead.",
    trait1: "Strength: Memorizing fans’ names and faces like a pro.",
    trait2: "Weaknesses: Studying.",
    trait3: "Family: Wears a cherished ornament from the very first idol costume her mom made.",
    trait4: "Pre-Race Ritual: Checks her shoe grip like a perfectionist.",
    trait5: "Secret: Can fall asleep anywhere.",
    speedpriority: "900-1000",
    staminapriority: "400-500",
    powerpriority: "500-600",
    gutspriority: "200-300",
   witspriority: "400-500",
   skill1: "Professor of Curvature",
   skill2: "Final Push",
   skill3: "Homestretch Haste",
   besttotrain: "Focus on speed,then on power,stamina,wits and guts.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Mile/Med", 
   okdistance: "Sprint", 
   worstdistance: "Long", 
   track: "She performs best on dirt tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Smart_Falcon_%28Icon%29.png&width=300",
   profilename: "Smart Falcon",
   profilesubtitle: " 'Falcon of the Sand' ",
   rarity: "★★★",
   type: "Speed",
   distance: "Mike/Med",
   style: "Front",
   birthday: "April 4",
   gooddistance2: "Mile/Med",
   okdistance2: "Sprint",
   worstdistance2: "Long",
   goodpace: "Front",
   okpace: "Pace",
   worstpace: "End/Late",
   pollEmbed: ['',
    '',
    ''
   ]
  }, 

  suzuka: {
    personality: "An Umamusume seen as a true prodigy, she is always far ahead of the pack—both literally and figuratively. Completely absorbed in her love of running, she can appear distant or aloof, but those who know her understand that her heart is simply dedicated to the track. Despite her quiet nature, her authenticity draws many to her. She shares a room with Special Week, where her calm presence is balanced by her roommate’s cheerful energy.",
    trait1: "Strength: Running.",
    trait2: "Weaknesses: Crowded places.",
    trait3: "Family: They support her by giving her extra money for new running shoes.",
    trait4: "Pre-Race Ritual: She remembers the joy of the very first time she ran.",
    trait5: "Secret: She’s surprisingly good at pen spinning.",
    speedpriority: "900-1000",
    staminapriority: "300-350",
    powerpriority: "450-550",
    gutspriority: "500-550",
   witspriority: "300-350",
   skill1: "Final Push",
   skill2: "Unrestrained",
   skill3: "Straightaway Acceleration",
   besttotrain: "Focus on speed,then on guts,power,stamina and wits.",
   racestrategy: "On Sprint choose End. On Mile choose Late. On Medium choose Pacee. On Long choose Front.", 
   bestdistance: "Mile/Med", 
   okdistance: "Sprint", 
   worstdistance: "Long", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Silence_Suzuka_%28Icon%29.png&width=300",
   profilename: "Silence Suzuka",
   profilesubtitle: " 'Runaway from Another Dimension' ",
   rarity: "★★★",
   type: "Speed",
   distance: "Mile/Med",
   style: "Front",
   birthday: "May 1",
   gooddistance2: "Mile/Med",
   okdistance2: "Sprint",
   worstdistance2: "Long",
   goodpace: "Front",
   okpace: "Pace",
   worstpace: "Late/End",
   pollEmbed: ['',
    '',
    ''
   ]
  }, 

  specialweek: {
      personality: "Born in Hokkaido, Special Week is a bright and cheery, hardworking Umamusume. After losing her birth mother, she was lovingly raised by her mother’s close friend. Carrying the warmth of both her moms in her heart, she dreams of becoming Japan’s top racer and fulfilling the promise she made to them. Though she may stumble along the way, her indomitable spirit ensures she always runs forward with a smile.",
    trait1: "Strength: Giving in-depth food critiques.",
    trait2: "Weaknesses: Touch-and-go ticket gates at the train station.",
    trait3: "Family: Her bright eye color comes from her birth mother.",
    trait4: "Pre-Race Ritual: Runs as if returning home, declaring “I’m off!”.",
    trait5: "Secret: Can distinguish different types of milk with just one taste.",
    speedpriority: "500-570",
    staminapriority: "650-700",
    powerpriority: "350-400",
    gutspriority: "300-350",
   witspriority: "300-350",
   skill1: "Go with the Flow",
   skill2: "Straightaway Acceleration",
   skill3: "Homestretch Haste",
   besttotrain: "Focus on stamina,then on speed,power,guts and wits.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Med/Long", 
   okdistance: "Mile", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Special_Week_%28Icon%29.png&width=300",
   profilename: "Special Week",
   profilesubtitle: " 'Supreme Commander of Japan' ",
   rarity: "★★★",
   type: "Stamina/Speed",
   distance: "Med/Long",
   style: "Pace/Late",
   birthday: "May 2",
   gooddistance2: "Med/Long",
   okdistance2: "Mile",
   worstdistance2: "Sprint",
   goodpace: "Pace/Late",
   okpace: "End",
   worstpace: "Front",
   pollEmbed: ['',
    '',
    ''
   ]
  },

  supercreek: {
      personality: "Motherly and kind, her very presence carries a calming warmth. No matter how bad things get, she’ll forgive, comfort, and spoil you with kindness until your heart feels light again. Her leniency sometimes extends even to herself, but she never wavers in her belief that the growth of others is more important than her own personal gain. Gentle but firm, she is a nurturing figure who inspires trust both on and off the track. Despite her kindness, she holds spirited rivalries with Oguri Cap and Tamamo Cross, testing her resolve as much as her compassion.",
    trait1: "Strength: Helping others.",
    trait2: "Weaknesses: Drawing.",
    trait3: "Family: Her family’s daycare center is beloved for making everyone feel at home.",
    trait4: "Pre-Race Ritual: Always ensures her trainer is safe and comfortable.",
    trait5: "Secret: ery skilled at rolling rice cakes; knows a surprising amount about golf thanks to her father’s influence.",
    speedpriority: "800-900",
    staminapriority: "300-400",
    powerpriority: "400-500",
    gutspriority: "300-400",
   witspriority: "200-300",
   skill1: "Go with the Flow",
   skill2: "Professor of Curvature",
   skill3: "Straightaway Recovery",
   besttotrain: "Focus on speed,then on power,stamina,guts and wits.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Med/Long", 
   okdistance: "-", 
   worstdistance: "Mile/Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Super_Creek_%28Icon%29.png&width=300",
   profilename: "Super Creek",
   profilesubtitle: " 'High-speed Stayer' ",
   rarity: "★★",
   type: "Speed",
   distance: "Med/Long",
   style: "Pace",
   birthday: "May 27",
   gooddistance2: "Med/Long",
   okdistance2: "-",
   worstdistance2: "Mile/Sprint",
   goodpace: "Pace",
   okpace: "Late",
   worstpace: "Front/End",
   pollEmbed: ['',
    '',
    ''
   ]
  },

  rudolf: {
      personality: "The reigning Emperor. Her rule is absolute! Well-versed in both the ways of racing and leadership through her duties as president of the Tracen Academy Student Council, she embodies balance, discipline, and vision. Always conscious of the example she sets, she strives to be a model Umamusume—one whose footsteps others can proudly follow. Her dream is nothing less than the dawn of a new age, where every Umamusume can race, laugh, and live in true happiness.Her dignity commands admiration, with Tokai Teio looking up to her more than anyone. Yet behind her composed air lies a heart that values the small joys of life, from clever wordplay to neatly pressed paperwork stamps.",
    trait1: "Strength: Chess, strategic foresight.",
    trait2: "Weaknesses: Casual, everyday interactions.",
    trait3: "Family: Raised from youth with the principles of leadership and rule instilled by her parents.",
    trait4: "Pre-Race Ritual: Always given the right of way, as though the track itself recognizes her status.",
    trait5: "Secret: Takes quiet delight in stamping paperwork vertically and with perfect neatness.",
    speedpriority: "700-800",
    staminapriority: "750-800",
    powerpriority: "520-550",
    gutspriority: "400-450",
   witspriority: "300-400",
   skill1: "Go with the Flow",
   skill2: "Professor of Curvature",
   skill3: "Straightaway Acceleration",
   besttotrain: "Focus on stamina,then on speed,power,guts and wits.",
   racestrategy: "On Sprint choose End. On Mile choose Late. On Medium choose Pace. On Long choose Front.", 
   bestdistance: "Med/Long", 
   okdistance: "Mile", 
   worstdistance: "Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Symboli_Rudolf_%28Icon%29.png&width=300",
   profilename: "Symboli Rudolf",
   profilesubtitle: " 'Emperor' ",
   rarity: "★★★",
   type: "Stamina/Speed",
   distance: "Med/Long",
   style: "Pace/Late",
   birthday: "March 13",
   gooddistance2: "Med/Long",
   okdistance2: "Mile",
   worstdistance2: "Sprint",
   goodpace: "Pace/Late",
   okpace: "Front/End",
   worstpace: "-",
   pollEmbed: ['',
    '',
    ''
   ]
  },

  opera: {
      personality: "An over-the-top, narcissistic, and somewhat comical opera king. Her behavior is always magnified for the stage—sometimes with theatrical grandeur, sometimes with earnest, booming self-praise. She genuinely believes that those who do not recognize their own beauty and strength live in misfortune, so she takes it upon herself to “enlighten” the masses about self-love. Her flamboyant presence often draws laughter and admiration alike. She is especially admired by Meisho Doto, who sees her as a dazzling beacon of confidence.",
    trait1: "Strength: Performing impromptu operas.",
    trait2: "Weaknesses: Mundane tasks.",
    trait3: "Family: Holds deep respect for her parents, who raised her to embrace her magnificence.",
    trait4: "Pre-Race Ritual: She observes every audience member’s expression, ready to turn the track into her stage.",
    trait5: "Secret: Once attempted to enlarge her earring designs just to “fit the role better”.",
    speedpriority: "900-1000",
    staminapriority: "700-800",
    powerpriority: "600-700",
    gutspriority: "300-400",
   witspriority: "200-300",
   skill1: "Straightaway Acceleration",
   skill2: "Homestretch Haste",
   skill3: "Gourmand",
   besttotrain: "Focus on speed,then on stamina,power,guts and wits.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Med/Long", 
   okdistance: "-", 
   worstdistance: "Mile/Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=T.M._Opera_O_%28Icon%29.png&width=300",
   profilename: "T.M. Opera O",
   profilesubtitle: " 'Supreme Ruler of Century's End' ",
   rarity: "★★★",
   type: "Speed",
   distance: "Med/Long",
   style: "Pace/Late",
   birthday: "March 13",
   gooddistance2: "Med/Long",
   okdistance2: "-",
   worstdistance2: "Mile/Sprint",
   goodpace: "Pace/Late",
   okpace: "Front",
   worstpace: "End",
   pollEmbed: ['',
    '',
    ''
   ]
  },

  taiki: {
    personality: "A friendly girl born in the U.S. A cowgirl with a heart as big as the open plains. Warm, welcoming, and always ready to give the best hugs, she shines brightest when she’s surrounded by friends. But under that sunny smile lies a hint of loneliness, which might be why she’s always planning parties and gatherings—her way of keeping everyone together. With a natural talent for sprints, her lightning-fast bursts of speed have even impressed her close friend, Silence Suzuka.",
    trait1: "Strength: Positive thinking, boundless energy.",
    trait2: "Weaknesses: Being alone.",
    trait3: "Family: ",
    trait4: "Pre-Race Ritual: ",
    trait5: "Secret: ",
    speedpriority: "1100-1200",
    staminapriority: "200-300",
    powerpriority: "500-600",
    gutspriority: "300-400",
   witspriority: "400-500",
   skill1: "Professor of Curvature",
   skill2: "Focus",
   skill3: "Straightaway Acceleration",
   besttotrain: "Focus on speed,then on power,wits,guts and stamina.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Sprint/Mile", 
   okdistance: "-", 
   worstdistance: "Med/Long", 
   track: "She performs best on turf tracks. She performs almost as well on dirt tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Taiki_Shuttle_%28Icon%29.png&width=300",
   profilename: "Taiki Shuttle",
   profilesubtitle: " 'Strongest Miler' ",
   rarity: "★★★",
   type: "Speed",
   distance: "Sprint/Mile",
   style: "Pace",
   birthday: "March 23",
   gooddistance2: "Sprint/Mile",
   okdistance2: "-",
   worstdistance2: "Med/Long",
   goodpace: "Pace",
   okpace: "Front",
   worstpace: "Late/End",
   pollEmbed: ['',
    '',
    ''
   ]
  },


  teio: {
      personality: "A bright, bubbly Umamusume with an instinctive talent for racing. Long inspired by the student council president, Symboli Rudolf, she channels this admiration into her relentless drive to become number one. Fans are captivated by her infectious confidence and have affectionately named her cheerful march the “Teio Step.”",
    trait1: "Strength: Making friends, spreading positivity.",
    trait2: "Weaknesses: Doctors.",
    trait3: "Family: They shed tears when she stopped calling them “Mama” and “Papa”.",
    trait4: "Pre-Race Ritual: Bends and stretches with special focus on her knees.",
    trait5: "Secret: Used to play at the beach and earned the nickname “Ruler of the Beach”.",
    speedpriority: "780-850",
    staminapriority: "800-900",
    powerpriority: "500-550",
    gutspriority: "350",
   witspriority: "300-350",
   skill1: "Go with the Flow",
   skill2: "Pace Chaser Corners ◯",
   skill3: "Straightaway Acceleration",
   besttotrain: "Focus on stamina,then on speed,power,guts and wits.",
   racestrategy: "On Sprint choose End. On Mile choose Late. On Medium choose Pace. On Long choose Front.", 
   bestdistance: "Med", 
   okdistance: "Long", 
   worstdistance: "Mile/Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Tokai_Teio_%28Icon%29.png&width=300",
   profilename: "Tokai Teio",
   profilesubtitle: " 'Monarch' ",
   rarity: "★★★",
   type: "Stamina/Speed",
   distance: "Med",
   style: "Pace",
   birthday: "April 20",
   gooddistance2: "Med",
   okdistance2: "Long",
   worstdistance2: "Mile/Sprint",
   goodpace: "Pace",
   okpace: "Late/Front",
   worstpace: "End",
   pollEmbed: ['',
    '',
    ''
   ]
  },

  vodka: {
      personality: "Determined to be the coolest, this Umamusume models herself after her motorcycle-loving father, mirroring his hobbies and flair for adventure. Bold and daring, she plunges headfirst into any challenge without fear. She shares a playful, cat-and-dog dynamic with her roommate, Daiwa Scarlet.",
    trait1: "Strength: Air bike, pulling off daring stunts.",
    trait2: "Weaknesses: Gossip about romance.",
    trait3: "Family: Often gets scolded by her mom for causing mischief alongside her dad.",
    trait4: "Pre-Race Ritual: “My blood is boiling…” (sometimes leads to nosebleeds)",
    trait5: "Secret: Practices sliding glasses down counters; saving her New Year’s money for a motorcycle.",
    speedpriority: "900-1000",
    staminapriority: "400-500",
    powerpriority: "500-600",
    gutspriority: "300-400",
   witspriority: "300-400",
   skill1: "Corner Adept ◯",
   skill2: "Straightaway Acceleration",
   skill3: "Homestretch Haste",
   besttotrain: "Focus on speed,then on power,stamina,guts and wits.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Mile/Med", 
   okdistance: "-", 
   worstdistance: "Sprint/Long", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Vodka_%28Icon%29.png&width=300",
   profilename: "Vodka",
   profilesubtitle: " 'Empress of Breaking Common Sense' ",
   rarity: "★★",
   type: "Speed",
   distance: "Mile/Med",
   style: "Late",
   birthday: "April 4",
   gooddistance2: "Mile/Med",
   okdistance2: "-",
   worstdistance2: "Sprint/Long",
   goodpace: "Late",
   okpace: "Pace/Front",
   worstpace: "End",
   pollEmbed: ['',
    '',
    ''
   ]
  },

  ticket: {
      personality: "A straightforward and expressive Umamusume, she sympathizes deeply with others and wears her heart on her sleeve. Passionate about all sports, she holds the Japan Derby in the highest regard and dreams of competing—and winning—there at any cost. She shares a strong, inseparable friendship with Narita Taishin and Biwa Hayahide.",
    trait1: "Strength: Full of support, overflowing with emotion.",
    trait2: "Weaknesses: Holding back, not giving her all!!!",
    trait3: "Family: Watching the Derby together is their most cherished tradition.",
    trait4: "Pre-Race Ritual: Watches past Derby footage to lift her spirits.",
    trait5: "Secret: Particular about her innerwear; very knowledgeable about sports rules.",
    speedpriority: "800-900",
    staminapriority: "500-600",
    powerpriority: "500-600",
    gutspriority: "300-400",
   witspriority: "300-400",
   skill1: "Professor of Curvature",
   skill2: "Up-Tempo",
   skill3: "Straightaway Acceleration",
   besttotrain: "Focus on speed,then on stamina,power,guts and wits.",
   racestrategy: "On Sprint choose Front. On Mile choose Pace. On Medium choose Late. On Long choose End.", 
   bestdistance: "Med", 
   okdistance: "Long", 
   worstdistance: "Mile/Sprint", 
   track: "She performs best on turf tracks.",
   profileimage: "https://umamusu.wiki/w/thumb.php?f=Winning_Ticket_%28Icon%29.png&width=300",
   profilename: "Winning Ticket",
   profilesubtitle: " 'Flag-bearer of a New Era' ",
   rarity: "★",
   type: "Speed",
   distance: "Med",
   style: "Late",
   birthday: "March 21",
   gooddistance2: "Med",
   okdistance2: "Long",
   worstdistance2: "Mile/Sprint",
   goodpace: "Late",
   okpace: "Pace",
   worstpace: "Front/End",
   pollEmbed: ['',
    '',
    ''
   ]
  },
};



document.addEventListener('DOMContentLoaded', function() {
    if (window.location.pathname.includes('character.html')) {
        loadCharacterData();
    }
});

function loadCharacterData() {
    const urlParams = new URLSearchParams(window.location.search);
    const charName = urlParams.get('char');
    
    if (!charName || !characters[charName]) {
        console.error('Character not found:', charName);
        return;
    }
    
    const character = characters[charName];

    document.querySelectorAll('.profilename').forEach(el => {
        el.textContent = character.profilename;
    });
    
    if (character.profilesubtitle) {
        document.querySelector('.profilesubtitle').textContent = character.profilesubtitle;
    }
    if (character.rarity) {
        document.querySelector('.rarity').textContent = character.rarity;
    }
    if (character.type) {
        document.querySelector('.type').textContent = character.type;
    }
    if (character.distance) {
        document.querySelector('.distance').textContent = character.distance;
    }
    if (character.style) {
        document.querySelector('.style').textContent = character.style;
    }
    if (character.birthday) {
        document.querySelector('.birthday').textContent = character.birthday;
    }
    
    if (character.personality) {
        document.querySelector('.personality').textContent = character.personality;
    }
     if (character.trait1) {
        document.querySelector('.trait1').textContent = character.trait1;
    }
       if (character.trait2) {
        document.querySelector('.trait2').textContent = character.trait2;
    }
       if (character.trait3) {
        document.querySelector('.trait3').textContent = character.trait3;
    }
       if (character.trait4) {
        document.querySelector('.trait4').textContent = character.trait4;
    }
       if (character.trait5) {
        document.querySelector('.trait5').textContent = character.trait5;
    }
    if (character.speedpriority) {
        document.querySelector('.speedpriority').innerHTML = `<strong>Speed:</strong> ${character.speedpriority}`;
    }
    if (character.staminapriority) {
        document.querySelector('.staminapriority').innerHTML = `<strong>Stamina:</strong> ${character.staminapriority}`;
    }
    if (character.powerpriority) {
        document.querySelector('.powerpriority').innerHTML = `<strong>Power:</strong> ${character.powerpriority}`;
    }
    if (character.gutspriority) {
        document.querySelector('.gutspriority').innerHTML = `<strong>Guts:</strong> ${character.gutspriority}`;
    }
    if (character.witspriority) {
        document.querySelector('.witspriority').innerHTML = `<strong>Wits:</strong> ${character.witspriority}`;
    }
    if (character.skill1) {
        document.querySelector('.skill1').innerHTML = `<strong>Skill 1:</strong> ${character.skill1}`;
    }
    if (character.skill2) {
        document.querySelector('.skill2').innerHTML = `<strong>Skill 2:</strong> ${character.skill2}`;
    }
    if (character.skill3) {
        document.querySelector('.skill3').innerHTML = `<strong>Skill 3:</strong> ${character.skill3}`;
    }
    if (character.besttotrain) {
        document.querySelector('.besttotrain').textContent = character.besttotrain;
    }
    if (character.racestrategy) {
        document.querySelector('.racestrategy').textContent = character.racestrategy;
    }
    if (character.bestdistance) {
        document.querySelector('.bestdistance').textContent = `Best: ${character.bestdistance}`;
    }
    if (character.okdistance) {
        document.querySelector('.okdistance').textContent = `Okay: ${character.okdistance}`;
    }
    if (character.worstdistance) {
        document.querySelector('.worstdistance').textContent = `Avoid: ${character.worstdistance}`;
    }
    if (character.track) {
        document.querySelector('.track').textContent = character.track;
    }
    if (character.profileimage) {
        document.querySelector('.profileimage img').src = character.profileimage;
    }
    if (character.besttotrain) {
        document.querySelector('.besttotrain').textContent = character.besttotrain;
    }
    if (character.gooddistance2) {
        document.querySelector('.gooddistance2').textContent = character.gooddistance2;
    }
     if (character.okdistance2) {
        document.querySelector('.okdistance2').textContent = character.okdistance2;
    }
     if (character.worstdistance2) {
        document.querySelector('.worstdistance2').textContent = character.worstdistance2;
    }
    if (character.goodpace) {
        document.querySelector('.goodpace').textContent = character.goodpace;
    }
    if (character.okpace) {
        document.querySelector('.okpace').textContent = character.okpace;
    }
    if (character.worstpace) {
        document.querySelector('.worstpace').textContent = character.worstpace;
    }
  if (character.pollEmbed) {
    document.getElementById('poll-container').innerHTML = character.pollEmbed;
}

    
}


