const characters = {
  airgroove: {
    personality: "",
    speedpriority: "",
    staminapriority: "",
    powerpriority: "",
    gutspriority: "",
   intelligencepriority: "",
   skill1: "",
   skill2: "",
   skill3: "",
   besttotrain: "",  
   racestrategy: "", 
   bestdistance: "", 
   okdistance: "", 
   worstdistance: "", 
   track: "",
   profileimage: "",
   profilename: "",
   profilesubtitle: "",
   rarity: "",
   type: "",
   distance: "",
   style: "",
   birthday: "",
  },    

  tachyon: {
    personality: "",
    speedpriority: "",
    staminapriority: "",
    powerpriority: "",
    gutspriority: "",
   intelligencepriority: "",
   skill1: "",
   skill2: "",
   skill3: "",
   besttotrain: "",  
   racestrategy: "", 
   bestdistance: "", 
   okdistance: "", 
   worstdistance: "", 
   track: "",
   profileimage: "",
   profilename: "",
   profilesubtitle: "",
   rarity: "",
   type: "",
   distance: "",
   style: "",
   birthday: "",
  },    
  
  baiwa: {
    personality: "",
    speedpriority: "",
    staminapriority: "",
    powerpriority: "",
    gutspriority: "",
   intelligencepriority: "",
   skill1: "",
   skill2: "",
   skill3: "",
   besttotrain: "",  
   racestrategy: "", 
   bestdistance: "", 
   okdistance: "", 
   worstdistance: "", 
   track: "",
   profileimage: "",
   profilename: "",
   profilesubtitle: "",
   rarity: "",
   type: "",
   distance: "",
   style: "",
   birthday: "",
  },    
  
};